.idea/gradle.xml
.idea/misc.xml
app/src/main/AndroidManifest.xml
app/src/main/java/com/clagroup/cowhandlerv2/MainActivity.java
app/src/main/java/com/clagroup/cowhandlerv2/OverviewPage.java
app/src/main/res/layout/activity_main.xml
app/src/main/res/layout/overview_page.xml

OverviewPage Java and XML files added; MainActivity XML and Java files manipulated for button click/page change functionality; intent added in AndroidManifest XML to support functionality

Activity creation with button click functionality

---

.idea/gradle.xml
.idea/inspectionProfiles/Project_Default.xml
app/build.gradle
app/google-services.json
app/src/main/AndroidManifest.xml
app/src/main/java/com/clagroup/cowhandlerv2/LoginActivity.java
app/src/main/res/layout/activity_login.xml
app/src/main/res/layout/activity_main.xml
build.gradle
gradle/wrapper/gradle-wrapper.properties

Created a login page. Unable to get it to load. Trying to use Google one-tap login.

Mathis branch

---

app/src/main/AndroidManifest.xml
app/src/main/java/com/clagroup/cowhandlerv2/LoginActivity.java
app/src/main/res/layout/activity_login.xml
app/src/main/res/layout/activity_main.xml

Make login the initial launch page with google sign in.
-Google one-tap works automatically on login page(not on emulated app)
-Added button to continue to main page from login page
-Minor layout change
Discovered that issue was that one-tap doesn't work on AS emulator. Must use actual phone for testing.
I plan to look into integrating sign-in into main page to reduce activity page count.
Also need to work on firebase connectivity.

Fix and implement Login activity.

---

.idea/misc.xml
app/src/main/AndroidManifest.xml
app/src/main/java/com/clagroup/cowhandlerv2/AddCow.java
app/src/main/java/com/clagroup/cowhandlerv2/CowEntry.java
app/src/main/java/com/clagroup/cowhandlerv2/DeleteCow.java
app/src/main/java/com/clagroup/cowhandlerv2/EditEntry.java
app/src/main/java/com/clagroup/cowhandlerv2/MainActivity.java
app/src/main/java/com/clagroup/cowhandlerv2/ViewCow.java
app/src/main/res/layout/activity_add_cow.xml
app/src/main/res/layout/activity_cow_entry.xml
app/src/main/res/layout/activity_delete_cow.xml
app/src/main/res/layout/activity_edit_entry.xml
app/src/main/res/layout/activity_main.xml
app/src/main/res/layout/activity_view_cow.xml
app/src/main/res/values/strings.xml

Added AddCow, CowEntry, ViewCow, EditEntry, and DeleteEntry; 
Linked the LandingPage's buttons to appropriate activities;
Added placeholders for entries on AddCow page
Conflicts came from code added on MainActivity page
MainActivity page should also display user credentials in a view
Revison numbers:
380971d38faea47cf14c9310a07362ab8a977176
b752e133d3ae9f692f56943b4707e0e4ee27ba2b
7463f4cbc8a91d4ca1a1995385520c89dcaaf01c
a5bc4a5047ca217627a54e34b5ea3db721ad64e7

Added Activities For Adding Entries; Fixed Landing Page Button Navigation

---

app/src/main/AndroidManifest.xml
app/src/main/java/com/clagroup/cowhandlerv2/CowEntry.java
app/src/main/java/com/clagroup/cowhandlerv2/LoginActivity.java
app/src/main/java/com/clagroup/cowhandlerv2/MainActivity.java
app/src/main/java/com/clagroup/cowhandlerv2/NewCow.java
app/src/main/res/layout/activity_cow_entry.xml

Enable cow entry to input to firebase.
-Data entry code moved to CowEntry activity
-Ensured each field functions and uploads to firestore database correctly
-Tied collection to authenticated user and document path to cowId.
Most of the work here was done in CowEntry and NewCow activities.
Minor clean-up of login and main page code that wasn't in use.
EditText boxes need to be restricted on input.

Cow Entry fully functional.

---

app/src/main/res/layout/activity_cow_entry.xml

Restricted input in Cow Entry page to prevent certain errors and ensure consistent input.
-Added "android:digits" to the EditText in the Cow Entry layout.xml.
-The code is restricted, but we do need to check with client to ensure exact intention on inputs(such as if weight should include "lbs" after the number or not)

Restricted Input on Cow Entry activity.

---

.idea/misc.xml
app/src/main/java/com/clagroup/cowhandlerv2/DeleteCow.java
app/src/main/java/com/clagroup/cowhandlerv2/EditEntry.java
app/src/main/java/com/clagroup/cowhandlerv2/NewCow.java
app/src/main/res/layout/activity_delete_cow.xml
app/src/main/res/layout/activity_edit_entry.xml
app/src/main/res/values/strings.xml

Enable EditCod and DeleteCow activities to interact with database.
Adjusted layout of both pages to enable input.
Added function to delete cow from database to DeleteCow activity.
Added function to edit a field of a cow to EditEntry activity.
-The edit function still needs a way to select a given cow. Will look into moving both functions into ViewCow activity once that is completed.
-Changed "descriptions" to "description" in NewCow activity as that sounds better.

Created functioning Delete and Edit pages.

---

app/src/main/java/com/clagroup/cowhandlerv2/ViewCow.java

Enable cowView to access and pull from Firebase database
Adjusted the viewCow page
Added the ability to fetch cow information based on cowID
-Possible editing in textView 
-Layout work is strongly recommended

Able to Fetch Single cowId information

---

.idea/misc.xml
app/src/main/java/com/clagroup/cowhandlerv2/AddCow.java
app/src/main/java/com/clagroup/cowhandlerv2/CowEntry.java
app/src/main/java/com/clagroup/cowhandlerv2/DeleteCow.java
app/src/main/java/com/clagroup/cowhandlerv2/EditEntry.java
app/src/main/java/com/clagroup/cowhandlerv2/LoginActivity.java
app/src/main/java/com/clagroup/cowhandlerv2/MainActivity.java
app/src/main/java/com/clagroup/cowhandlerv2/NewCow.java
app/src/main/java/com/clagroup/cowhandlerv2/OverviewPage.java
app/src/main/java/com/clagroup/cowhandlerv2/ViewCow.java
app/src/main/res/layout/activity_main.xml
app/src/main/res/layout/overview_page.xml
app/src/main/res/values-night/themes.xml
app/src/main/res/values/colors.xml
app/src/main/res/values/themes.xml

##Changes
Added functionality to display user credentials on the landing page.
##Types of Changes
##Checklist
Tested in development environment to assure that the added functionality does not create any bugs.
##Further Comments
Originally the user display was an image view, but for the sake of finishing the functionality in adequate time, it was changed to a TextView. The feature will be updated as progress is made still.

8 functioning landing page

---

.idea/misc.xml
app/src/main/java/com/clagroup/cowhandlerv2/MainActivity.java
app/src/main/java/com/clagroup/cowhandlerv2/OverviewPage.java
app/src/main/java/com/clagroup/cowhandlerv2/ViewCow.java
app/src/main/res/layout/activity_delete_cow.xml
app/src/main/res/layout/activity_main.xml
app/src/main/res/layout/overview_page.xml
app/src/main/res/values/strings.xml

Enables Overview to access and use ViewCow
Adjusted the viewCow page
Adjusted the Overview page
Added the ability to fetch cow information based on cowID  from button click on overview page
-Possible editing in textView 
-Layout work is strongly recommended

Added Overview button and connected to viewCow

---

.idea/misc.xml
app/src/main/java/com/clagroup/cowhandlerv2/DeleteCow.java
app/src/main/java/com/clagroup/cowhandlerv2/OverviewPage.java
app/src/main/res/layout/activity_main.xml

Enables Overview to access and use ViewCow
Enables Overview to access and use DeleteCow
Adjusted the DeleteCow page
Adjusted the Overview page
Adjusted the Overview layout xml to correct button
Adjusted the main layout xml to add OverView Page
Added the ability to delete cow based cowID  from button hold on overview page
-Layout work is strongly recommended
- A way to avoid needing to go to delete page and remain on overview

Fixed OverView page and connected it DeleteCow

---

app/build.gradle
app/src/main/java/com/clagroup/cowhandlerv2/CowEntry.java
app/src/main/java/com/clagroup/cowhandlerv2/NewCow.java
app/src/main/res/layout/activity_cow_entry.xml

Add picture functionality to CowEntry.
Added "take a picture" button to cow entry page.
Added camera integration to cow entry to take a picture and display it.
Integrated Firebase Storage into CowEntry page.
Added function to upload cow picture to Firebase Storage.
Added "pathToCowPicture" string to NewCow.
-While functional, this is still a WIP and does nothing outside the entry page.

Added taking and storing picture to CowEntry page.

---

app/build.gradle
app/src/main/java/com/clagroup/cowhandlerv2/CowEntry.java
app/src/main/java/com/clagroup/cowhandlerv2/DeleteCow.java
app/src/main/java/com/clagroup/cowhandlerv2/NewCow.java
app/src/main/java/com/clagroup/cowhandlerv2/ViewCow.java
app/src/main/res/layout/activity_view_cow.xml

Add viewing pictures to ViewCow and deleting pictures with DeleteCow.
Added Image to ViewCow layout.
Made function to pull and display picture associated with cow being view in viewCow
Added code to ensure deletion of picture when deleting a Cow from FireStore.
-Still need to implement picture view on overview buttons.

Enabled Viewing and Deleting of pictures in their respective pages.

---

app/src/main/java/com/clagroup/cowhandlerv2/DeleteCow.java
app/src/main/java/com/clagroup/cowhandlerv2/ViewCow.java
app/src/main/res/layout/activity_view_cow.xml
app/src/main/res/values/strings.xml

Added the ability to go to the edit or delete cow based on cowId from the viewCow page.
Added 2 click buttons to viewCow page
Added new if statement in viewCow function
Added new logs
Click to editCow
Click to deleteCow (automatically deletes cow based on ID value)
- Improvement on layout
- Alert feature needs to be added to delete button

Able to click edit and delete in viewCow

---

app/src/main/AndroidManifest.xml
app/src/main/java/com/clagroup/cowhandlerv2/MainActivity.java
app/src/main/java/com/clagroup/cowhandlerv2/OverviewPage.java
app/src/main/java/com/clagroup/cowhandlerv2/SearchCow.java
app/src/main/java/com/clagroup/cowhandlerv2/ViewCow.java
app/src/main/res/layout/activity_main.xml
app/src/main/res/layout/activity_search_cow.xml
app/src/main/res/layout/overview_page.xml
app/src/main/res/values/strings.xml

Added in ability to create PDFs of cow information via ViewCow and Overview pages. Also moved the individual cow search function to it's own page.
-Added pdf creation code to Viewcow
- Created new activity(SearchCow) for the searching of individual cowIDs.
- Added pdf generation button to viewcow(single) and overview(all) pages.
- Minor adjustment to main page to reflect search page.
-PDFs are generated per individual cow. Generating all will generate multiple individual pdfs.
-PDFs don't present the information in a pleasing format. Very basic.

Implemented pdf creation into Overview and ViewCow pages.

---

app/src/main/java/com/clagroup/cowhandlerv2/DeleteCow.java
app/src/main/java/com/clagroup/cowhandlerv2/MainActivity.java
app/src/main/res/layout/activity_main.xml

Added alert dialog functionality to the delete button on the MainActivity page and implemented that into the corresponding Delete function in the Delete activity.

45 alert dialogs

---

app/src/main/java/com/clagroup/cowhandlerv2/EditEntry.java
app/src/main/java/com/clagroup/cowhandlerv2/ViewCow.java
app/src/main/res/layout/activity_cow_entry.xml
app/src/main/res/layout/activity_edit_entry.xml

Reworked the EditCow page to be fully functional when accessed from ViewCow.
-Added view changes depending on dropdown selected
-Added display of cowId being updated
-Enables update of Radio Buttons via Radio Buttons in edit menu.
-Restricted input of numeric entries(mirrored in CowEntry)
-The page doesn't work from the main menu, as there's no way to specify cowId. Recommend simply removing the main menu option(same for DeleteCow).

EditEntry page fully functional from ViewCow

---

.idea/misc.xml
app/src/main/java/com/clagroup/cowhandlerv2/MainActivity.java
app/src/main/res/layout/activity_main.xml
app/src/main/res/menu/navigation_menu.xml
app/src/main/res/values-night/themes.xml
app/src/main/res/values/strings.xml
app/src/main/res/values/themes.xml

- Created navigation drawer on landing page
- Added item placeholders for potential components

40 sign in page design

---

app/src/main/java/com/clagroup/cowhandlerv2/CowEntry.java
app/src/main/java/com/clagroup/cowhandlerv2/NewCow.java
app/src/main/res/layout/activity_cow_entry.xml

Reworked the CowEntry, NewCow, and CowEntry layout pages to have a drop down menu to select the calf, cow, or bull with their own respected inputs
- Added more input information for database
- Adjusted the layout of CowEntry page
- Adjusted the CowEntry to show input option based on drop down
- Added drop down 
-The page should be directly accessed from Cow Entry button as the previous page is not needed
-Maybe some improvement for design

Updated Cow Entry With drop down

---

app/src/main/java/com/clagroup/cowhandlerv2/MainActivity.java
app/src/main/java/com/clagroup/cowhandlerv2/ViewCow.java
app/src/main/res/layout/activity_main.xml

Changed PDF generation to include pictures for each cow pdf made.
- Altered generate PDF code in ViewCow to include picture.
- Altered main page to temporarily disable buttons that were non-functional.
-Additional effort must be made on the main page, as we need to determine what buttons are needed.

Added pictures input to PDF generation.

---

app/src/main/java/com/clagroup/cowhandlerv2/MainActivity.java
app/src/main/java/com/clagroup/cowhandlerv2/ViewCow.java
app/src/main/res/layout/activity_main.xml

Removed delete button from Main Activity.
- Removed Main Activity delete button
- Moved the alert dialogue to the ViewCow delete button.

Removed delete button from main. Alert moved to the delete btn in ViewCow

---

.idea/misc.xml
app/src/main/java/com/clagroup/cowhandlerv2/MainActivity.java
app/src/main/res/layout/activity_main.xml
app/src/main/res/layout/nav_header_main.xml
app/src/main/res/menu/navigation_menu.xml

Added a navigation drawer in the toolbar of the application to display the logout button, as well as some general content.
- [  ] New Features (sign out, nav drawer)
- [  ] I have read the CONTRIBUTING doc
- [  ] I have met up with my team to discuss general content or requirements
- [  ] Tests pass locally with changes

Navigation Drawer

---

app/src/main/java/com/clagroup/cowhandlerv2/OverviewPage.java
app/src/main/res/layout/activity_cow_entry.xml

Just some minor changes in the code to overview page, entry and entry layout.

Edited the cow entry page and layout. Also overviewpage
